--- 
services: 
  analise: 
    environment: 
      JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
      LOG_LEVEL: INFO
      SERVER_PORT: 9999
      URL_SISTEMA_CARTAO: "http://contas:8888/api/cartoes"
    image: zupacademy/analise-financeira
    ports: 
      - "9999:9999"
  mysql: 
    image: mysql:latest
    ports: 
      - "3307:3306"
    volumes: 
      - mysql-volume:/etc/mysql/
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: Adm!n1str@d0r
      MYSQL_DATABASE: proposta
  contas: 
    environment: 
      JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
      LOG_LEVEL: INFO
      SERVER_PORT: 8888
    image: zupacademy/contas
    ports: 
      - "8888:8888"
  grafana: 
    depends_on: 
      - prometheus
    image: grafana/grafana
    network_mode: bridge
    ports: 
      - "3000:3000"
    volumes: 
      - "grafana-volume:/var/lib/grafana"
  jaeger: 
    environment: 
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    image: jaegertracing/all-in-one
    ports: 
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  kafka: 
    depends_on: 
      - zookeeper
    environment: 
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    image: "confluentinc/cp-kafka:5.2.1"
    ports: 
      - "9092:9092"
  keycloak: 
    depends_on: 
      - grafana
      - prometheus
      - jaeger
      - kafka
      - zookeeper
      - contas
      - analise
      - transacoes
      - postgres
    environment: 
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_USER: keycloak
      DB_VENDOR: postgres
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_USER: admin
      POSTGRES_PORT_5432_TCP_ADDR: "127.0.0.1"
    image: jboss/keycloak
    ports: 
      - "18443:8443"
      - "18080:8080"
      - "19990:9990"
  postgres: 
    environment: 
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: keycloak
    image: "postgres:alpine"
    ports: 
      - "5432:5432"
    volumes: 
      - "postgres-volume:/var/lib/postgresql/data"
  prometheus: 
    image: prom/prometheus
    network_mode: bridge
    ports: 
      - "9090:9090"
    volumes: 
      - "prometheus-volume:/etc/prometheus/"
  proposta: 
    depends_on: 
      - mysql
      - grafana
      - analise
      - contas
    build:
      dockerfile: /Dockerfiles/proposta.dockerfile
    ports: 
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      FINANCEIRA_HOST: analise
      CARTAO_HOST: contas
  transacoes: 
    depends_on: 
      - kafka
    environment: 
      JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
      KAFKA_HOST: "kafka:29092"
      LOG_LEVEL: INFO
      SERVER_PORT: 7777
    image: zupacademy/transacoes
    ports: 
      - "7777:7777"
  vault: 
    environment: 
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_DEV_ROOT_TOKEN_ID: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_TOKEN: ee413645-dbe8-4848-afc6-6bb2768ada75
    image: "vault:1.5.3"
    ports: 
      - "8200:8200"
  zookeeper: 
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_TICK_TIME: 2000
    image: "confluentinc/cp-zookeeper:5.2.1"
version: "3"
volumes: 
  mysql-volume: ~
  grafana-volume: ~
  postgres-volume: ~
  prometheus-volume: ~
